#!/bin/bash

set -ex

source $(dirname "$0")/env_setup.sh

setup_lint_env

# Ignore the expected and resulting output files generated by unittests for the aggregate_file script
# These are formatted poorly are only meant to be used for testing purposes
black --check --diff src/ tests/ --extend-exclude tests/unittests/out_file
isort --profile black --check --diff src/ tests/ --skip-glob tests/unittests/out_file
